Re-add app_host env var

diff --git a/.kamal/secrets b/.kamal/secrets
--- a/.kamal/secrets
+++ b/.kamal/secrets
@@ -31,6 +31,13 @@ if [ -z "$DATABASE_URL" ]; then
 fi
 DATABASE_URL=$DATABASE_URL
 
+# Grab the app host from ENV, error if not set
+if [ -z "$APP_HOST" ]; then
+  echo "Error: APP_HOST environment variable is not set"
+  exit 1
+fi
+APP_HOST=$APP_HOST
+
 # Improve security by using a password manager. Never check config/master.key into git!
 if [ ! -f config/master.key ]; then
   echo "Error: config/master.key file not found"
